[package]
name = "anilog"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "A CLI program for logging anime"
repository = "https://github.com/scorpi4n/anilog.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
